namespace Fixtures;

public class TooLong
{
    public int F1 { get; set; }
    public int F2 { get; set; }
    public int F3 { get; set; }
    public int F4 { get; set; }
    public int F5 { get; set; }
    public int F6 { get; set; }
    public int F7 { get; set; }
    public int F8 { get; set; }
    public int F9 { get; set; }
    public int F10 { get; set; }
    public int F11 { get; set; }
    public int F12 { get; set; }
    public int F13 { get; set; }
    public int F14 { get; set; }
    public int F15 { get; set; }
    public int F16 { get; set; }
    public int F17 { get; set; }
    public int F18 { get; set; }
    public int F19 { get; set; }
    public int F20 { get; set; }
    public int F21 { get; set; }
    public int F22 { get; set; }
    public int F23 { get; set; }
    public int F24 { get; set; }
    public int F25 { get; set; }
    public int F26 { get; set; }
    public int F27 { get; set; }
    public int F28 { get; set; }
    public int F29 { get; set; }
    public int F30 { get; set; }
    public int F31 { get; set; }
    public int F32 { get; set; }
    public int F33 { get; set; }
    public int F34 { get; set; }
    public int F35 { get; set; }
    public int F36 { get; set; }
    public int F37 { get; set; }
    public int F38 { get; set; }
    public int F39 { get; set; }
    public int F40 { get; set; }
    public int F41 { get; set; }
    public int F42 { get; set; }
    public int F43 { get; set; }
    public int F44 { get; set; }
    public int F45 { get; set; }
    public int F46 { get; set; }
    public int F47 { get; set; }
    public int F48 { get; set; }
    public int F49 { get; set; }
    public int F50 { get; set; }
    public int F51 { get; set; }
    public int F52 { get; set; }
    public int F53 { get; set; }
    public int F54 { get; set; }
    public int F55 { get; set; }
    public int F56 { get; set; }
    public int F57 { get; set; }
    public int F58 { get; set; }
    public int F59 { get; set; }
    public int F60 { get; set; }
    public int F61 { get; set; }
    public int F62 { get; set; }
    public int F63 { get; set; }
    public int F64 { get; set; }
    public int F65 { get; set; }
    public int F66 { get; set; }
    public int F67 { get; set; }
    public int F68 { get; set; }
    public int F69 { get; set; }
    public int F70 { get; set; }
    public int F71 { get; set; }
    public int F72 { get; set; }
    public int F73 { get; set; }
    public int F74 { get; set; }
    public int F75 { get; set; }
    public int F76 { get; set; }
    public int F77 { get; set; }
    public int F78 { get; set; }
    public int F79 { get; set; }
    public int F80 { get; set; }
    public int F81 { get; set; }
    public int F82 { get; set; }
    public int F83 { get; set; }
    public int F84 { get; set; }
    public int F85 { get; set; }
    public int F86 { get; set; }
    public int F87 { get; set; }
    public int F88 { get; set; }
    public int F89 { get; set; }
    public int F90 { get; set; }
    public int F91 { get; set; }
    public int F92 { get; set; }
    public int F93 { get; set; }
    public int F94 { get; set; }
    public int F95 { get; set; }
    public int F96 { get; set; }
    public int F97 { get; set; }
    public int F98 { get; set; }
    public int F99 { get; set; }
    public int F100 { get; set; }
    public int F101 { get; set; }
    public int F102 { get; set; }
    public int F103 { get; set; }
    public int F104 { get; set; }
    public int F105 { get; set; }
    public int F106 { get; set; }
    public int F107 { get; set; }
    public int F108 { get; set; }
    public int F109 { get; set; }
    public int F110 { get; set; }
    public int F111 { get; set; }
    public int F112 { get; set; }
    public int F113 { get; set; }
    public int F114 { get; set; }
    public int F115 { get; set; }
    public int F116 { get; set; }
    public int F117 { get; set; }
    public int F118 { get; set; }
    public int F119 { get; set; }
    public int F120 { get; set; }
    public int F121 { get; set; }
    public int F122 { get; set; }
    public int F123 { get; set; }
    public int F124 { get; set; }
    public int F125 { get; set; }
    public int F126 { get; set; }
    public int F127 { get; set; }
    public int F128 { get; set; }
    public int F129 { get; set; }
    public int F130 { get; set; }
    public int F131 { get; set; }
    public int F132 { get; set; }
    public int F133 { get; set; }
    public int F134 { get; set; }
    public int F135 { get; set; }
    public int F136 { get; set; }
    public int F137 { get; set; }
    public int F138 { get; set; }
    public int F139 { get; set; }
    public int F140 { get; set; }
    public int F141 { get; set; }
    public int F142 { get; set; }
    public int F143 { get; set; }
    public int F144 { get; set; }
    public int F145 { get; set; }
    public int F146 { get; set; }
    public int F147 { get; set; }
    public int F148 { get; set; }
    public int F149 { get; set; }
    public int F150 { get; set; }
    public int F151 { get; set; }
    public int F152 { get; set; }
    public int F153 { get; set; }
    public int F154 { get; set; }
    public int F155 { get; set; }
    public int F156 { get; set; }
    public int F157 { get; set; }
    public int F158 { get; set; }
    public int F159 { get; set; }
    public int F160 { get; set; }
    public int F161 { get; set; }
    public int F162 { get; set; }
    public int F163 { get; set; }
    public int F164 { get; set; }
    public int F165 { get; set; }
    public int F166 { get; set; }
    public int F167 { get; set; }
    public int F168 { get; set; }
    public int F169 { get; set; }
    public int F170 { get; set; }
    public int F171 { get; set; }
    public int F172 { get; set; }
    public int F173 { get; set; }
    public int F174 { get; set; }
    public int F175 { get; set; }
    public int F176 { get; set; }
    public int F177 { get; set; }
    public int F178 { get; set; }
    public int F179 { get; set; }
    public int F180 { get; set; }
    public int F181 { get; set; }
    public int F182 { get; set; }
    public int F183 { get; set; }
    public int F184 { get; set; }
    public int F185 { get; set; }
    public int F186 { get; set; }
    public int F187 { get; set; }
    public int F188 { get; set; }
    public int F189 { get; set; }
    public int F190 { get; set; }
    public int F191 { get; set; }
    public int F192 { get; set; }
    public int F193 { get; set; }
    public int F194 { get; set; }
    public int F195 { get; set; }
    public int F196 { get; set; }
    public int F197 { get; set; }
    public int F198 { get; set; }
    public int F199 { get; set; }
    public int F200 { get; set; }
    public int F201 { get; set; }
    public int F202 { get; set; }
    public int F203 { get; set; }
    public int F204 { get; set; }
    public int F205 { get; set; }
    public int F206 { get; set; }
    public int F207 { get; set; }
    public int F208 { get; set; }
    public int F209 { get; set; }
    public int F210 { get; set; }
    public int F211 { get; set; }
    public int F212 { get; set; }
    public int F213 { get; set; }
    public int F214 { get; set; }
    public int F215 { get; set; }
    public int F216 { get; set; }
    public int F217 { get; set; }
    public int F218 { get; set; }
    public int F219 { get; set; }
    public int F220 { get; set; }
    public int F221 { get; set; }
    public int F222 { get; set; }
    public int F223 { get; set; }
    public int F224 { get; set; }
    public int F225 { get; set; }
    public int F226 { get; set; }
    public int F227 { get; set; }
    public int F228 { get; set; }
    public int F229 { get; set; }
    public int F230 { get; set; }
    public int F231 { get; set; }
    public int F232 { get; set; }
    public int F233 { get; set; }
    public int F234 { get; set; }
    public int F235 { get; set; }
    public int F236 { get; set; }
    public int F237 { get; set; }
    public int F238 { get; set; }
    public int F239 { get; set; }
    public int F240 { get; set; }
    public int F241 { get; set; }
    public int F242 { get; set; }
    public int F243 { get; set; }
    public int F244 { get; set; }
    public int F245 { get; set; }
    public int F246 { get; set; }
    public int F247 { get; set; }
    public int F248 { get; set; }
    public int F249 { get; set; }
    public int F250 { get; set; }
    public int F251 { get; set; }
    public int F252 { get; set; }
    public int F253 { get; set; }
    public int F254 { get; set; }
    public int F255 { get; set; }
    public int F256 { get; set; }
    public int F257 { get; set; }
    public int F258 { get; set; }
    public int F259 { get; set; }
    public int F260 { get; set; }
    public int F261 { get; set; }
    public int F262 { get; set; }
    public int F263 { get; set; }
    public int F264 { get; set; }
    public int F265 { get; set; }
    public int F266 { get; set; }
    public int F267 { get; set; }
    public int F268 { get; set; }
    public int F269 { get; set; }
    public int F270 { get; set; }
    public int F271 { get; set; }
    public int F272 { get; set; }
    public int F273 { get; set; }
    public int F274 { get; set; }
    public int F275 { get; set; }
    public int F276 { get; set; }
    public int F277 { get; set; }
    public int F278 { get; set; }
    public int F279 { get; set; }
    public int F280 { get; set; }
    public int F281 { get; set; }
    public int F282 { get; set; }
    public int F283 { get; set; }
    public int F284 { get; set; }
    public int F285 { get; set; }
    public int F286 { get; set; }
    public int F287 { get; set; }
    public int F288 { get; set; }
    public int F289 { get; set; }
    public int F290 { get; set; }
    public int F291 { get; set; }
    public int F292 { get; set; }
    public int F293 { get; set; }
    public int F294 { get; set; }
    public int F295 { get; set; }
    public int F296 { get; set; }
    public int F297 { get; set; }
    public int F298 { get; set; }
    public int F299 { get; set; }
    public int F300 { get; set; }
    public int F301 { get; set; }
    public int F302 { get; set; }
    public int F303 { get; set; }
    public int F304 { get; set; }
    public int F305 { get; set; }
    public int F306 { get; set; }
    public int F307 { get; set; }
    public int F308 { get; set; }
    public int F309 { get; set; }
    public int F310 { get; set; }
    public int F311 { get; set; }
    public int F312 { get; set; }
    public int F313 { get; set; }
    public int F314 { get; set; }
    public int F315 { get; set; }
    public int F316 { get; set; }
    public int F317 { get; set; }
    public int F318 { get; set; }
    public int F319 { get; set; }
    public int F320 { get; set; }
    public int F321 { get; set; }
    public int F322 { get; set; }
    public int F323 { get; set; }
    public int F324 { get; set; }
    public int F325 { get; set; }
    public int F326 { get; set; }
    public int F327 { get; set; }
    public int F328 { get; set; }
    public int F329 { get; set; }
    public int F330 { get; set; }
    public int F331 { get; set; }
    public int F332 { get; set; }
    public int F333 { get; set; }
    public int F334 { get; set; }
    public int F335 { get; set; }
    public int F336 { get; set; }
    public int F337 { get; set; }
    public int F338 { get; set; }
    public int F339 { get; set; }
    public int F340 { get; set; }
    public int F341 { get; set; }
    public int F342 { get; set; }
    public int F343 { get; set; }
    public int F344 { get; set; }
    public int F345 { get; set; }
    public int F346 { get; set; }
    public int F347 { get; set; }
    public int F348 { get; set; }
    public int F349 { get; set; }
    public int F350 { get; set; }
    public int F351 { get; set; }
    public int F352 { get; set; }
    public int F353 { get; set; }
    public int F354 { get; set; }
    public int F355 { get; set; }
    public int F356 { get; set; }
    public int F357 { get; set; }
    public int F358 { get; set; }
    public int F359 { get; set; }
    public int F360 { get; set; }
    public int F361 { get; set; }
    public int F362 { get; set; }
    public int F363 { get; set; }
    public int F364 { get; set; }
    public int F365 { get; set; }
    public int F366 { get; set; }
    public int F367 { get; set; }
    public int F368 { get; set; }
    public int F369 { get; set; }
    public int F370 { get; set; }
    public int F371 { get; set; }
    public int F372 { get; set; }
    public int F373 { get; set; }
    public int F374 { get; set; }
    public int F375 { get; set; }
    public int F376 { get; set; }
    public int F377 { get; set; }
    public int F378 { get; set; }
    public int F379 { get; set; }
    public int F380 { get; set; }
    public int F381 { get; set; }
    public int F382 { get; set; }
    public int F383 { get; set; }
    public int F384 { get; set; }
    public int F385 { get; set; }
    public int F386 { get; set; }
    public int F387 { get; set; }
    public int F388 { get; set; }
    public int F389 { get; set; }
    public int F390 { get; set; }
    public int F391 { get; set; }
    public int F392 { get; set; }
    public int F393 { get; set; }
    public int F394 { get; set; }
    public int F395 { get; set; }
    public int F396 { get; set; }
    public int F397 { get; set; }
    public int F398 { get; set; }
    public int F399 { get; set; }
    public int F400 { get; set; }
    public int F401 { get; set; }
}
